var sign = Date.parse(new Date()); 

document.write("<script src='Frame/js/ycframe/ycframe.app.min.js?v=0.0.1'></script>");
document.write("<script src='Frame/js/app.js?v=0.0.1'></script>");
document.write("<script src='Frame/js/jquery.min.js?v=2.1.4'></script>"); 
document.write("<script src='Frame/js/ycframe/ycframe.min.js'></script> ");
document.write("<script language=javascript src='Frame/js/bootstrap.min.js?v=3.3.6'>/script>");
document.write("<script language=javascript src='Frame/js/plugins/peity/jquery.peity.min.js?0820'></script> ");
document.write("<script language=javascript src='Frame/js/plugins/jqgrid/i18n/grid.locale-cn.js?0820'></script>");
document.write("<script language=javascript src='Frame/js/plugins/jqgrid/jquery.jqGrid.min.js?0830'></script> ");
document.write("<script src='Frame/js/plugins/layer/layer.min.js'></script>");
document.write(" <script src='Frame/js/ycframe/ycframe.javarun.min.js'></script>");
document.write("<script src='Frame/js/ui.min.js?s="+"1206"+"'></script> "); 
document.write("<script src='Frame/js/ycframe/ycframe.role.min.js'></script> ");
document.write(" <script src='Frame/js/jszip.min.js'></script>");
document.write(" <script src='Frame/js/jquery.base64.js'></script>"); 
document.write("<script src='Frame/js/plugins/form/jquery.form.min.js'></script> ");
document.write("<script type='text/javascript' src='Frame/js/plugins/treeselect/jquery.treeselect2.min.js?s=1206'></script>");
document.write("<script type='text/javascript' src='Frame/js/plugins/treeselect/jquery.bgiframe.js'></script>");
document.write(" <script src='Frame/js/plugins/layer/laydate/laydate.js'></script>");
document.write(" <script src='Frame/js/plugins/validate/jquery.validate.min.js'></script>");
document.write(" <script src='Frame/js/plugins/validate/messages_zh.min.js'></script>");
document.write(" <script src='Frame/js/plugins/treeview/bootstrap-treeview.min.js'></script>");
document.write(" <script src='Frame/js/plugins/datapicker/bootstrap-datepicker.min.js'></script>");
document.write(" <script src='Frame/js/plugins/datapicker/bootstrap-datepicker.zh-CN.js'></script>");
document.write(" <script src='Frame/js/plugins/select2/select2.full.min.js'></script>");
document.write(" <script src='Frame/js/plugins/echarts/echarts.min.js'></script>");
document.write(" <script src='Frame/js/plugins/webuploader/webuploader.js'></script>"); 
document.write(" <script src='Frame/js/plugins/tableExport/tableExport.min.js'></script>");
document.write(" <script src='Frame/js/plugins/uiplugin/table.min.js'></script>");
document.write(" <script src='Frame/js/plugins/url/jquery.url.js'></script>");
